spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    platform: postgres
    url: {{ spring.datasource.url }}
    username: {{ spring.datasource.username }}
    password: {{ spring.datasource.password }}
    driverClassName: org.postgresql.Driver

sql:
  init:
    platform: postgresql
