INSERT INTO BOXES VALUES (0, 1);
INSERT INTO BOXES VALUES (1, 2);
INSERT INTO BOXES VALUES (2, 4);
INSERT INTO BOXES VALUES (3, 8);
INSERT INTO BOXES VALUES (4, 16);
INSERT INTO BOXES VALUES (5, 32);
INSERT INTO BOXES VALUES (6, 64);
