CREATE TABLE IF NOT EXISTS BOXES (
    ID                  SERIAL PRIMARY KEY,
    FREQUENCY           INTEGER
);

CREATE TABLE IF NOT EXISTS SESSIONS (
    ID                  SERIAL PRIMARY KEY,
    SESSION_NUMBER      INTEGER
);

CREATE TABLE IF NOT EXISTS FLASHCARDS (
    ID                  SERIAL PRIMARY KEY,
    QUESTION            TEXT NOT NULL,
    ANSWER              TEXT NOT NULL,
    TAGS                TEXT [],
    BOX_ID              INTEGER REFERENCES BOXES(ID)
);

INSERT INTO SESSIONS (ID, SESSION_NUMBER) VALUES (1, 0);

INSERT INTO BOXES (ID, FREQUENCY) VALUES (1, 1), (2, 2), (3, 4), (4, 8), (5, 16), (6, 32), (7, 64);
